SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE EXAM_DETAIL;
DROP TABLE EXAM_USER_RESULT;
DROP TABLE EXAM;
DROP TABLE EXAM_TSQZ;
DROP TABLE USER_RESULT;




/* Create Tables */

CREATE TABLE EXAM_DETAIL
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	XH INT COMMENT '题目序号',
	EXAM_ID INT COMMENT '考试ID',
	TM_ID VARCHAR(50) COMMENT '题目ID',
	PRIMARY KEY (ID_)
) COMMENT = '考试题目';


CREATE TABLE EXAM_USER_RESULT
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	USER_ID INT COMMENT 'USER_ID',
	EXAM_DETAIL_ID INT COMMENT '考试题目ID',
	ANSWER VARCHAR(20) COMMENT '用户答案',
	EXAM_TIME DOUBLE COMMENT '答题时间',
	RESULT CHAR(1) COMMENT '答题结果 对与错',
	EXAM_SCORE DOUBLE COMMENT '获得分值',
	START_TIME DATETIME COMMENT '开始答题',
	END_TIME DATETIME COMMENT '答题结束时间',
	PRIMARY KEY (ID_)
) COMMENT = '用户考试记录';


CREATE TABLE EXAM
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	START_TIME DATETIME COMMENT '开始时间',
	END_TIME DATETIME COMMENT '结束时间',
	TITLE VARCHAR(1000) COMMENT '考试主题',
	EXAM_TYPE CHAR(1) COMMENT '考试类型 1正式考试2抢答',
	FQR_ID INT COMMENT '发起人ID',
	PRIMARY KEY (ID_)
) COMMENT = '考试';


CREATE TABLE EXAM_TSQZ
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	GROUP_ID INT COMMENT '群组ID',
	EXAM_ID INT COMMENT '考试ID',
	PRIMARY KEY (ID_)
) COMMENT = '考试推送群组';


CREATE TABLE USER_RESULT
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	USER_ID INT COMMENT 'USER_ID',
	TM_ID VARCHAR(50) COMMENT '题目ID',
	ANSWER VARCHAR(20) COMMENT '用户答案',
	RESULT CHAR(1) COMMENT '答题结果',
	RESULT_TIME DOUBLE COMMENT '答题时间',
	RESULT_SCORE DOUBLE COMMENT '获得分值',
	START_TIME DATETIME COMMENT '开始答题',
	END_TIME DATETIME COMMENT '结束答题',
	PRIMARY KEY (ID_)
) COMMENT = '用户答题记录';



