SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE ZSKLY;
DROP TABLE ZSZSK;
DROP TABLE GR_ZSK_GXJL;
DROP TABLE DEPT_ZSK_GXJL;
DROP TABLE YXZSK;
DROP TABLE ZSDTSJL;
DROP TABLE ZSKTSNR;
DROP TABLE ZSKTSQZ;




/* Create Tables */

CREATE TABLE ZSKLY
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	TITLE VARCHAR(200) COMMENT '来源标题',
	CONTENT VARCHAR(2000) COMMENT '内容',
	ATTACHMENT VARCHAR(1000) COMMENT '附件',
	PRIMARY KEY (ID_)
) COMMENT = '知识库来源表';


CREATE TABLE ZSZSK
(
	ID_ VARCHAR(50) NOT NULL UNIQUE COMMENT 'ID_',
	USER_ID INT COMMENT '录入人ID',
	CREATE_DATE DATE COMMENT '创建日期',
	SP_DATE DATE COMMENT '审批日期',
	SPR_ID INT COMMENT '审批人ID',
	DEPTID INT COMMENT '部门ID',
	CONTENT VARCHAR(2000) COMMENT '内容',
	ZSKLY_ID INT COMMENT '来源ID',
	TITLE VARCHAR(0) COMMENT '知识库标题',
	PRIMARY KEY (ID_)
) COMMENT = '正式知识库';


CREATE TABLE GR_ZSK_GXJL
(
	ID_ VARCHAR(50) NOT NULL UNIQUE COMMENT 'ID_',
	DEPT_ID INT COMMENT '部门ID',
	ZSK_ID VARCHAR(50) COMMENT '知识ID',
	GXZ DOUBLE COMMENT '贡献值',
	GXLY INT COMMENT '贡献方式 1预选库出题，2被选入正式库',
	GX_DATE DATE COMMENT '获取时间',
	PRIMARY KEY (ID_)
) COMMENT = '个人知识库贡献记录';


CREATE TABLE DEPT_ZSK_GXJL
(
	ID_ VARCHAR(50) NOT NULL UNIQUE COMMENT 'ID_',
	DEPT_ID INT COMMENT '部门ID',
	ZSK_ID VARCHAR(50) COMMENT '知识ID',
	GXZ DOUBLE COMMENT '贡献值',
	GXLY INT COMMENT '贡献方式 1预选库出题，2被选入正式库',
	GX_DATE DATE COMMENT '获取时间',
	PRIMARY KEY (ID_)
) COMMENT = '部门知识库贡献记录';


CREATE TABLE YXZSK
(
	ID_ VARCHAR(50) NOT NULL UNIQUE COMMENT 'ID_',
	USER_ID INT COMMENT '录入人ID',
	CREATE_DATE DATE COMMENT '创建日期',
	SP_DATE DATE COMMENT '审批日期',
	SPR_ID INT COMMENT '审批人ID',
	DEPTID INT COMMENT '部门ID',
	CONTENT VARCHAR(2000) COMMENT '内容',
	ZSKLY_ID INT COMMENT '来源ID',
	TITLE VARCHAR(0) COMMENT '知识库标题',
	PRIMARY KEY (ID_)
) COMMENT = '预选知识库';


CREATE TABLE ZSDTSJL
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	TSRID INT COMMENT '推送人',
	TSRQ DATE COMMENT '推送日期',
	MS VARCHAR(500) COMMENT '描述',
	PRIMARY KEY (ID_)
) COMMENT = '知识点推送记录';


CREATE TABLE ZSKTSNR
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	TSJLID INT COMMENT '推送记录ID',
	ZSKID VARCHAR(50) COMMENT '知识点ID',
	PRIMARY KEY (ID_)
) COMMENT = '知识库推送内容';


CREATE TABLE ZSKTSQZ
(
	ID_ INT NOT NULL UNIQUE AUTO_INCREMENT COMMENT 'ID_',
	GROUP_ID INT COMMENT '群组ID',
	TSJLID INT COMMENT '推送记录ID',
	PRIMARY KEY (ID_)
) COMMENT = '知识点推送群组';



