package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 部门.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Dept implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id_;

	/** 部门名称. */
	private String dept_name;

	/** PARENT_ID. */
	private Integer parentId;

	/** 描述. */
	private String ms;

	/**
	 * Constructor.
	 */
	public Dept() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId_(Integer id_) {
		this.id_ = id_;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId_() {
		return this.id_;
	}

	/**
	 * Set the 部门名称.
	 * 
	 * @param deptName
	 *            部门名称
	 */
	public void setDept_name(String dept_name) {
		this.dept_name = dept_name;
	}

	/**
	 * Get the 部门名称.
	 * 
	 * @return 部门名称
	 */
	public String getDept_name() {
		return this.dept_name;
	}

	/**
	 * Set the PARENT_ID.
	 * 
	 * @param parentId
	 *            PARENT_ID
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * Get the PARENT_ID.
	 * 
	 * @return PARENT_ID
	 */
	public Integer getParentId() {
		return this.parentId;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param ms
	 *            描述
	 */
	public void setMs(String ms) {
		this.ms = ms;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getMs() {
		return this.ms;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id_ == null) ? 0 : id_.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Dept other = (Dept) obj;
		if (id_ == null) {
			if (other.id_ != null) {
				return false;
			}
		} else if (!id_.equals(other.id_)) {
			return false;
		}
		return true;
	}

}
