package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 考试题目.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ExamDetail implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** 题目序号. */
	private Integer xh;

	/** 考试ID. */
	private Integer examId;

	/** 题目ID. */
	private String tmId;

	/**
	 * Constructor.
	 */
	public ExamDetail() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 题目序号.
	 * 
	 * @param xh
	 *            题目序号
	 */
	public void setXh(Integer xh) {
		this.xh = xh;
	}

	/**
	 * Get the 题目序号.
	 * 
	 * @return 题目序号
	 */
	public Integer getXh() {
		return this.xh;
	}

	/**
	 * Set the 考试ID.
	 * 
	 * @param examId
	 *            考试ID
	 */
	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	/**
	 * Get the 考试ID.
	 * 
	 * @return 考试ID
	 */
	public Integer getExamId() {
		return this.examId;
	}

	/**
	 * Set the 题目ID.
	 * 
	 * @param tmId
	 *            题目ID
	 */
	public void setTmId(String tmId) {
		this.tmId = tmId;
	}

	/**
	 * Get the 题目ID.
	 * 
	 * @return 题目ID
	 */
	public String getTmId() {
		return this.tmId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ExamDetail other = (ExamDetail) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
