package gov.hygs.htgl.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 用户考试记录.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ExamUserResult implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** USER_ID. */
	private Integer userId;

	/** 考试题目ID. */
	private Integer examDetailId;

	/** 用户答案. */
	private String answer;

	/** 答题时间. */
	private Double examTime;

	/** 答题结果 对与错. */
	private String result;

	/** 获得分值. */
	private Double examScore;

	/** 开始答题. */
	private Date startTime;

	/** 答题结束时间. */
	private Date endTime;

	private String type;
	
	/**
	 * Constructor.
	 */
	public ExamUserResult() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the USER_ID.
	 * 
	 * @param userId
	 *            USER_ID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the USER_ID.
	 * 
	 * @return USER_ID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the 考试题目ID.
	 * 
	 * @param examDetailId
	 *            考试题目ID
	 */
	public void setExamDetailId(Integer examDetailId) {
		this.examDetailId = examDetailId;
	}

	/**
	 * Get the 考试题目ID.
	 * 
	 * @return 考试题目ID
	 */
	public Integer getExamDetailId() {
		return this.examDetailId;
	}

	/**
	 * Set the 用户答案.
	 * 
	 * @param answer
	 *            用户答案
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/**
	 * Get the 用户答案.
	 * 
	 * @return 用户答案
	 */
	public String getAnswer() {
		return this.answer;
	}

	/**
	 * Set the 答题时间.
	 * 
	 * @param examTime
	 *            答题时间
	 */
	public void setExamTime(Double examTime) {
		this.examTime = examTime;
	}

	/**
	 * Get the 答题时间.
	 * 
	 * @return 答题时间
	 */
	public Double getExamTime() {
		return this.examTime;
	}

	/**
	 * Set the 答题结果 对与错.
	 * 
	 * @param result
	 *            答题结果 对与错
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * Get the 答题结果 对与错.
	 * 
	 * @return 答题结果 对与错
	 */
	public String getResult() {
		return this.result;
	}

	/**
	 * Set the 获得分值.
	 * 
	 * @param examScore
	 *            获得分值
	 */
	public void setExamScore(Double examScore) {
		this.examScore = examScore;
	}

	/**
	 * Get the 获得分值.
	 * 
	 * @return 获得分值
	 */
	public Double getExamScore() {
		return this.examScore;
	}

	/**
	 * Set the 开始答题.
	 * 
	 * @param startTime
	 *            开始答题
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * Get the 开始答题.
	 * 
	 * @return 开始答题
	 */
	public Date getStartTime() {
		return this.startTime;
	}

	/**
	 * Set the 答题结束时间.
	 * 
	 * @param endTime
	 *            答题结束时间
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * Get the 答题结束时间.
	 * 
	 * @return 答题结束时间
	 */
	public Date getEndTime() {
		return this.endTime;
	}

	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ExamUserResult other = (ExamUserResult) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
