package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 考试推送群组.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ExamTsqz implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** 群组ID. */
	private Integer groupId;

	/** 考试ID. */
	private Integer examId;

	/**
	 * Constructor.
	 */
	public ExamTsqz() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 群组ID.
	 * 
	 * @param groupId
	 *            群组ID
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * Get the 群组ID.
	 * 
	 * @return 群组ID
	 */
	public Integer getGroupId() {
		return this.groupId;
	}

	/**
	 * Set the 考试ID.
	 * 
	 * @param examId
	 *            考试ID
	 */
	public void setExamId(Integer examId) {
		this.examId = examId;
	}

	/**
	 * Get the 考试ID.
	 * 
	 * @return 考试ID
	 */
	public Integer getExamId() {
		return this.examId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ExamTsqz other = (ExamTsqz) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
