package gov.hygs.htgl.entity;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;

/**
 * Model class of 群组.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Grouptable implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** 群组名称. */
	private String groupName;

	/** 描述. */
	private String ms;
	
	private Integer parentId;
	
	private Collection<Grouptable> child;
	
	private Integer pxh;
	
	private Integer lrrID;

	private Date effective_date;
	
	
	public Collection<Grouptable> getChild() {
		return child;
	}



	public void setChild(Collection<Grouptable> child) {
		this.child = child;
	}



	public Date getEffective_date() {
		return effective_date;
	}



	public void setEffective_date(Date effective_date) {
		this.effective_date = effective_date;
	}



	/**
	 * Constructor.
	 */
	public Grouptable() {
	}
	
	

	public Integer getParentId() {
		return parentId;
	}



	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}



	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 群组名称.
	 * 
	 * @param groupName
	 *            群组名称
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	/**
	 * Get the 群组名称.
	 * 
	 * @return 群组名称
	 */
	public String getGroupName() {
		return this.groupName;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param ms
	 *            描述
	 */
	public void setMs(String ms) {
		this.ms = ms;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getMs() {
		return this.ms;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	public Integer getPxh() {
		return pxh;
	}


	public void setPxh(Integer pxh) {
		this.pxh = pxh;
	}

	public Integer getLrrID() {
		return lrrID;
	}

	public void setLrrID(Integer lrrID) {
		this.lrrID = lrrID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Grouptable other = (Grouptable) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
