package gov.hygs.htgl.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * Model class of 功能菜单.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Menu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id_;

	/** PARENT_ID. */
	private Integer parent_Id;

	/** 菜单名称. */
	private String menu_Name;

	/** 功能访问地址. */
	private String url;

	/** 有效标志. */
	private String yxbz;

	private Boolean selected;
	
	private List<Menu> menus = new ArrayList<Menu>();

	/**
	 * Constructor.
	 */
	public Menu() {
	}

	public Boolean getSelected() {
		return selected;
	}

	public void setSelected(Boolean selected) {
		this.selected = selected;
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId_(Integer id_) {
		this.id_ = id_;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId_() {
		return this.id_;
	}

	/**
	 * Set the PARENT_ID.
	 * 
	 * @param parent_Id
	 *            PARENT_ID
	 */
	public void setParent_Id(Integer parent_Id) {
		this.parent_Id = parent_Id;
	}

	/**
	 * Get the PARENT_ID.
	 * 
	 * @return PARENT_ID
	 */
	public Integer getParent_Id() {
		return this.parent_Id;
	}

	/**
	 * Set the 菜单名称.
	 * 
	 * @param menu_Name
	 *            菜单名称
	 */
	public void setMenu_Name(String menu_Name) {
		this.menu_Name = menu_Name;
	}

	/**
	 * Get the 菜单名称.
	 * 
	 * @return 菜单名称
	 */
	public String getMenu_Name() {
		return this.menu_Name;
	}

	/**
	 * Set the 功能访问地址.
	 * 
	 * @param url
	 *            功能访问地址
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * Get the 功能访问地址.
	 * 
	 * @return 功能访问地址
	 */
	public String getUrl() {
		return this.url;
	}

	/**
	 * Set the 有效标志.
	 * 
	 * @param yxbz
	 *            有效标志
	 */
	public void setYxbz(String yxbz) {
		this.yxbz = yxbz;
	}

	/**
	 * Get the 有效标志.
	 * 
	 * @return 有效标志
	 */
	public String getYxbz() {
		return this.yxbz;
	}

	
	public List<Menu> getMenus() {
		return menus;
	}

	public void setMenus(List<Menu> menus) {
		this.menus = menus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id_ == null) ? 0 : id_.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Menu other = (Menu) obj;
		if (id_ == null) {
			if (other.id_ != null) {
				return false;
			}
		} else if (!id_.equals(other.id_)) {
			return false;
		}
		return true;
	}

}
