package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 角色功能表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoleMenu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id_;

	/** MENU_ID. */
	private Integer menu_Id;

	/** ROLE_ID. */
	private Integer role_Id;

	/**
	 * Constructor.
	 */
	public RoleMenu() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId_(Integer id_) {
		this.id_ = id_;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId_() {
		return this.id_;
	}

	/**
	 * Set the MENU_ID.
	 * 
	 * @param menu_Id
	 *            MENU_ID
	 */
	public void setMenu_Id(Integer menu_Id) {
		this.menu_Id = menu_Id;
	}

	/**
	 * Get the MENU_ID.
	 * 
	 * @return MENU_ID
	 */
	public Integer getMenu_Id() {
		return this.menu_Id;
	}

	/**
	 * Set the ROLE_ID.
	 * 
	 * @param role_Id
	 *            ROLE_ID
	 */
	public void setRole_Id(Integer role_Id) {
		this.role_Id = role_Id;
	}

	/**
	 * Get the ROLE_ID.
	 * 
	 * @return ROLE_ID
	 */
	public Integer getRole_Id() {
		return this.role_Id;
	}


}
