package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 系统参数表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class SystemProps implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** 参数KEY. */
	private String key;

	/** 参数值. */
	private String value;

	/** 描述. */
	private String ms;

	/**
	 * Constructor.
	 */
	public SystemProps() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 参数KEY.
	 * 
	 * @param key
	 *            参数KEY
	 */
	public void setKey(String key) {
		this.key = key;
	}

	/**
	 * Get the 参数KEY.
	 * 
	 * @return 参数KEY
	 */
	public String getKey() {
		return this.key;
	}

	/**
	 * Set the 参数值.
	 * 
	 * @param value
	 *            参数值
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * Get the 参数值.
	 * 
	 * @return 参数值
	 */
	public String getValue() {
		return this.value;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param ms
	 *            描述
	 */
	public void setMs(String ms) {
		this.ms = ms;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getMs() {
		return this.ms;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		SystemProps other = (SystemProps) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
