package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 题目答案.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Tkda implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private String id;

	/** 题目ID. */
	private String tkId;

	/** 题目选择项ID. */
	private String tkxzxid;

	/**
	 * Constructor.
	 */
	public Tkda() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 题目ID.
	 * 
	 * @param tkId
	 *            题目ID
	 */
	public void setTkId(String tkId) {
		this.tkId = tkId;
	}

	/**
	 * Get the 题目ID.
	 * 
	 * @return 题目ID
	 */
	public String getTkId() {
		return this.tkId;
	}

	/**
	 * Set the 题目选择项ID.
	 * 
	 * @param tkxzxid
	 *            题目选择项ID
	 */
	public void setTkxzxid(String tkxzxid) {
		this.tkxzxid = tkxzxid;
	}

	/**
	 * Get the 题目选择项ID.
	 * 
	 * @return 题目选择项ID
	 */
	public String getTkxzxid() {
		return this.tkxzxid;
	}


}
