package gov.hygs.htgl.entity;

import java.io.Serializable;
import java.util.Collection;

/**
 * Model class of 题库分类表.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Tkfl implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** parent_id. */
	private Integer parentId;

	/** 题库名称. */
	private String tkmc;

	/** 描述. */
	private String ms;
	
	private Integer pxh;
	
	public Integer getPxh() {
		return pxh;
	}

	public void setPxh(Integer pxh) {
		this.pxh = pxh;
	}

	private Collection<Tkfl> child;

	public Collection<Tkfl> getChild() {
		return child;
	}

	public void setChild(Collection<Tkfl> child) {
		this.child = child;
	}

	/**
	 * Constructor.
	 */
	public Tkfl() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the parent_id.
	 * 
	 * @param parentId
	 *            parent_id
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * Get the parent_id.
	 * 
	 * @return parent_id
	 */
	public Integer getParentId() {
		return this.parentId;
	}

	/**
	 * Set the 题库名称.
	 * 
	 * @param tkmc
	 *            题库名称
	 */
	public void setTkmc(String tkmc) {
		this.tkmc = tkmc;
	}

	/**
	 * Get the 题库名称.
	 * 
	 * @return 题库名称
	 */
	public String getTkmc() {
		return this.tkmc;
	}

	/**
	 * Set the 描述.
	 * 
	 * @param ms
	 *            描述
	 */
	public void setMs(String ms) {
		this.ms = ms;
	}

	/**
	 * Get the 描述.
	 * 
	 * @return 描述
	 */
	public String getMs() {
		return this.ms;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Tkfl other = (Tkfl) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
