package gov.hygs.htgl.entity;

import java.io.Serializable;
import java.util.Collection;
import java.util.Date;

/**
 * Model class of 题库题目.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Tktm implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private String id;

	/** 所属分类. */
	private Integer flId;

	/** 录入人ID. */
	private Integer userId;

	/** 创建日期. */
	private Date createDate;

	/** 审批日期. */
	private Date spDate;

	/** 审批人ID. */
	private Integer sprId;

	/** 部门ID. */
	private Integer deptid;

	/** 题干内容. */
	private String content;

	/** 题目分值. */
	private Double tmfz;

	/** 题目难度. */
	private Integer tmnd;

	/** 题目来源ID. */
	private Integer tmlyId;

	/** 选择类型 1单选，2多选. */
	private String mode;

	/** 有效标志. */
	private String yxbz;

	/** 选用标志. */
	private String xybz;
	
	/** 导入标志.  */
	private String drbz;
	
	/** 考试标志. */
	private String ksbz;
	
	/** 题干内容. */
	private String tkfl;
	/** 题干内容. */
	private String user;
	/** 题干内容. */
	private String dept;
	/** 题干内容. */
	private String tmly;
	/** 题目来源来源内容 */
	private String tmlyContent;
	
	private Collection<Tkxzx> tkxzx;
	private Collection<Tkxzx> daxzx;

	public Collection<Tkxzx> getTkxzx() {
		return tkxzx;
	}

	public void setTkxzx(Collection<Tkxzx> tkxzx) {
		this.tkxzx = tkxzx;
	}

	public Collection<Tkxzx> getDaxzx() {
		return daxzx;
	}

	public String getDrbz() {
		return drbz;
	}

	public void setDrbz(String drbz) {
		this.drbz = drbz;
	}

	public void setDaxzx(Collection<Tkxzx> daxzx) {
		this.daxzx = daxzx;
	}

	/**
	 * Constructor.
	 */
	public Tktm() {
	}

	public String getKsbz() {
		return ksbz;
	}

	public void setKsbz(String ksbz) {
		this.ksbz = ksbz;
	}

	public String getTkfl() {
		return tkfl;
	}

	public void setTkfl(String tkfl) {
		this.tkfl = tkfl;
	}

	public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getDept() {
		return dept;
	}

	public void setDept(String dept) {
		this.dept = dept;
	}

	public String getTmly() {
		return tmly;
	}

	public void setTmly(String tmly) {
		this.tmly = tmly;
	}

	public String getTmlyContent() {
		return tmlyContent;
	}

	public void setTmlyContent(String tmlyContent) {
		this.tmlyContent = tmlyContent;
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * Set the 所属分类.
	 * 
	 * @param flId
	 *            所属分类
	 */
	public void setFlId(Integer flId) {
		this.flId = flId;
	}

	/**
	 * Get the 所属分类.
	 * 
	 * @return 所属分类
	 */
	public Integer getFlId() {
		return this.flId;
	}

	/**
	 * Set the 录入人ID.
	 * 
	 * @param userId
	 *            录入人ID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the 录入人ID.
	 * 
	 * @return 录入人ID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the 创建日期.
	 * 
	 * @param createDate
	 *            创建日期
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * Get the 创建日期.
	 * 
	 * @return 创建日期
	 */
	public Date getCreateDate() {
		return this.createDate;
	}

	/**
	 * Set the 审批日期.
	 * 
	 * @param spDate
	 *            审批日期
	 */
	public void setSpDate(Date spDate) {
		this.spDate = spDate;
	}

	/**
	 * Get the 审批日期.
	 * 
	 * @return 审批日期
	 */
	public Date getSpDate() {
		return this.spDate;
	}

	/**
	 * Set the 审批人ID.
	 * 
	 * @param sprId
	 *            审批人ID
	 */
	public void setSprId(Integer sprId) {
		this.sprId = sprId;
	}

	/**
	 * Get the 审批人ID.
	 * 
	 * @return 审批人ID
	 */
	public Integer getSprId() {
		return this.sprId;
	}

	/**
	 * Set the 部门ID.
	 * 
	 * @param deptid
	 *            部门ID
	 */
	public void setDeptid(Integer deptid) {
		this.deptid = deptid;
	}

	/**
	 * Get the 部门ID.
	 * 
	 * @return 部门ID
	 */
	public Integer getDeptid() {
		return this.deptid;
	}

	/**
	 * Set the 题干内容.
	 * 
	 * @param content
	 *            题干内容
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * Get the 题干内容.
	 * 
	 * @return 题干内容
	 */
	public String getContent() {
		return this.content;
	}

	/**
	 * Set the 题目分值.
	 * 
	 * @param tmfz
	 *            题目分值
	 */
	public void setTmfz(Double tmfz) {
		this.tmfz = tmfz;
	}

	/**
	 * Get the 题目分值.
	 * 
	 * @return 题目分值
	 */
	public Double getTmfz() {
		return this.tmfz;
	}

	/**
	 * Set the 题目难度.
	 * 
	 * @param tmnd
	 *            题目难度
	 */
	public void setTmnd(Integer tmnd) {
		this.tmnd = tmnd;
	}

	/**
	 * Get the 题目难度.
	 * 
	 * @return 题目难度
	 */
	public Integer getTmnd() {
		return this.tmnd;
	}

	/**
	 * Set the 题目来源ID.
	 * 
	 * @param tmlyId
	 *            题目来源ID
	 */
	public void setTmlyId(Integer tmlyId) {
		this.tmlyId = tmlyId;
	}

	/**
	 * Get the 题目来源ID.
	 * 
	 * @return 题目来源ID
	 */
	public Integer getTmlyId() {
		return this.tmlyId;
	}

	/**
	 * Set the 选择类型 1单选，2多选.
	 * 
	 * @param mode
	 *            选择类型 1单选，2多选
	 */
	public void setMode(String mode) {
		this.mode = mode;
	}

	/**
	 * Get the 选择类型 1单选，2多选.
	 * 
	 * @return 选择类型 1单选，2多选
	 */
	public String getMode() {
		return this.mode;
	}

	/**
	 * Set the 有效标志.
	 * 
	 * @param yxbz
	 *            有效标志
	 */
	public void setYxbz(String yxbz) {
		this.yxbz = yxbz;
	}

	/**
	 * Get the 有效标志.
	 * 
	 * @return 有效标志
	 */
	public String getYxbz() {
		return this.yxbz;
	}

	/**
	 * Set the 选用标志.
	 * 
	 * @param xybz
	 *            选用标志
	 */
	public void setXybz(String xybz) {
		this.xybz = xybz;
	}

	/**
	 * Get the 选用标志.
	 * 
	 * @return 选用标志
	 */
	public String getXybz() {
		return this.xybz;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Tktm other = (Tktm) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
