package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 题库推送内容.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Tktsnr implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** 推送记录ID. */
	private Integer tsjlid;

	/** 题目ID. */
	private String tmid;

	/**
	 * Constructor.
	 */
	public Tktsnr() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 推送记录ID.
	 * 
	 * @param tsjlid
	 *            推送记录ID
	 */
	public void setTsjlid(Integer tsjlid) {
		this.tsjlid = tsjlid;
	}

	/**
	 * Get the 推送记录ID.
	 * 
	 * @return 推送记录ID
	 */
	public Integer getTsjlid() {
		return this.tsjlid;
	}

	/**
	 * Set the 题目ID.
	 * 
	 * @param tmid
	 *            题目ID
	 */
	public void setTmid(String tmid) {
		this.tmid = tmid;
	}

	/**
	 * Get the 题目ID.
	 * 
	 * @return 题目ID
	 */
	public String getTmid() {
		return this.tmid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Tktsnr other = (Tktsnr) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
