package gov.hygs.htgl.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of 用户答题记录.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserResult implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** USER_ID. */
	private Integer userId;

	/** 题目ID. */
	private String tmId;

	/** 用户答案. */
	private String answer;

	/** 答题结果. */
	private String result;

	/** 答题时间. */
	private Double resultTime;

	/** 获得分值. */
	private Double resultScore;

	/** 开始答题. */
	private Date startTime;

	/** 结束答题. */
	private Date endTime;

	/**
	 * Constructor.
	 */
	public UserResult() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the USER_ID.
	 * 
	 * @param userId
	 *            USER_ID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the USER_ID.
	 * 
	 * @return USER_ID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the 题目ID.
	 * 
	 * @param tmId
	 *            题目ID
	 */
	public void setTmId(String tmId) {
		this.tmId = tmId;
	}

	/**
	 * Get the 题目ID.
	 * 
	 * @return 题目ID
	 */
	public String getTmId() {
		return this.tmId;
	}

	/**
	 * Set the 用户答案.
	 * 
	 * @param answer
	 *            用户答案
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

	/**
	 * Get the 用户答案.
	 * 
	 * @return 用户答案
	 */
	public String getAnswer() {
		return this.answer;
	}

	/**
	 * Set the 答题结果.
	 * 
	 * @param result
	 *            答题结果
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * Get the 答题结果.
	 * 
	 * @return 答题结果
	 */
	public String getResult() {
		return this.result;
	}

	/**
	 * Set the 答题时间.
	 * 
	 * @param resultTime
	 *            答题时间
	 */
	public void setResultTime(Double resultTime) {
		this.resultTime = resultTime;
	}

	/**
	 * Get the 答题时间.
	 * 
	 * @return 答题时间
	 */
	public Double getResultTime() {
		return this.resultTime;
	}

	/**
	 * Set the 获得分值.
	 * 
	 * @param resultScore
	 *            获得分值
	 */
	public void setResultScore(Double resultScore) {
		this.resultScore = resultScore;
	}

	/**
	 * Get the 获得分值.
	 * 
	 * @return 获得分值
	 */
	public Double getResultScore() {
		return this.resultScore;
	}

	/**
	 * Set the 开始答题.
	 * 
	 * @param startTime
	 *            开始答题
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * Get the 开始答题.
	 * 
	 * @return 开始答题
	 */
	public Date getStartTime() {
		return this.startTime;
	}

	/**
	 * Set the 结束答题.
	 * 
	 * @param endTime
	 *            结束答题
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * Get the 结束答题.
	 * 
	 * @return 结束答题
	 */
	public Date getEndTime() {
		return this.endTime;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserResult other = (UserResult) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
