package gov.hygs.htgl.entity;

import java.io.Serializable;

/**
 * Model class of 用户群组.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserGroup implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** ID_. */
	private Integer id;

	/** USER_ID. */
	private Integer userId;

	/** GROUP_ID. */
	private Integer groupId;

	/**
	 * Constructor.
	 */
	public UserGroup() {
	}

	/**
	 * Set the ID_.
	 * 
	 * @param id
	 *            ID_
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the ID_.
	 * 
	 * @return ID_
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the USER_ID.
	 * 
	 * @param userId
	 *            USER_ID
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * Get the USER_ID.
	 * 
	 * @return USER_ID
	 */
	public Integer getUserId() {
		return this.userId;
	}

	/**
	 * Set the GROUP_ID.
	 * 
	 * @param groupId
	 *            GROUP_ID
	 */
	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	/**
	 * Get the GROUP_ID.
	 * 
	 * @return GROUP_ID
	 */
	public Integer getGroupId() {
		return this.groupId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserGroup other = (UserGroup) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
